const jobRoles = [
"Frontend Developer",
"Backend Developer",
"Full Stack Developer",
"Web Developer",
"Software Developer",
"Software Engineer",
"Java Developer",
"Python Developer",
"C Developer",
"C++ Developer",
"C# Developer",
"JavaScript Developer",
"TypeScript Developer",
"PHP Developer",
"Laravel Developer",
"Django Developer",
"Flask Developer",
"React Developer",
"Angular Developer",
"Vue.js Developer",
"Node.js Developer",
"Next.js Developer",
"Express.js Developer",
"ASP.NET Developer",
"Android Developer",
"iOS Developer",
"Flutter Developer",
"React Native Developer",
"Kotlin Developer",
"Swift Developer",
"Go Developer",
"Rust Developer",
"Ruby Developer",
"Ruby on Rails Developer",
"Perl Developer",
"Scala Developer",
"R Developer",
"MATLAB Developer",
"Data Analyst",
"Business Analyst",
"Data Scientist",
"Machine Learning Engineer",
"AI Engineer",
"Deep Learning Engineer",
"NLP Engineer",
"Computer Vision Engineer",
"Prompt Engineer",
"Generative AI Engineer",
"DevOps Engineer",
"Cloud Engineer",
"AWS Engineer",
"Azure Engineer",
"Google Cloud Engineer",
"Site Reliability Engineer",
"Platform Engineer",
"Cyber Security Analyst",
"Ethical Hacker",
"Penetration Tester",
"Security Engineer",
"Network Engineer",
"System Administrator",
"Database Administrator",
"SQL Developer",
"Oracle Developer",
"MySQL Developer",
"MongoDB Developer",
"PostgreSQL Developer",
"Firebase Developer",
"Blockchain Developer",
"Web3 Developer",
"Solidity Developer",
"Game Developer",
"Unity Developer",
"Unreal Engine Developer",
"AR Developer",
"VR Developer",
"Embedded Systems Engineer",
"IoT Developer",
"Robotics Engineer",
"Automation Engineer",
"QA Engineer",
"Software Tester",
"Automation Tester",
"Manual Tester",
"Performance Tester",
"UI Developer",
"UI Designer",
"UX Designer",
"UI/UX Designer",
"Graphic Designer",
"Product Designer",
"Product Manager",
"Project Manager",
"Scrum Master",
"Technical Support Engineer",
"Help Desk Engineer",
"Solutions Architect",
"Enterprise Architect",
"SAP Consultant",
"Salesforce Developer",
"CRM Developer",
"ERP Consultant",
"Digital Marketing Executive"
];
